version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "/"
    assignees:
      - "wmmc88"
      - "cindyli-13"
    reviewers:
      - "wmmc88"
      - "cindyli-13"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "/"
    assignees:
      - "wmmc88"
      - "cindyli-13"
    reviewers:
      - "wmmc88"
      - "cindyli-13"

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "/"
    assignees:
      - "wmmc88"
      - "cindyli-13"
    reviewers:
      - "wmmc88"
      - "cindyli-13"

