version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "/"
    assignees:
      - "jahnavithota2011"
    reviewers:
      - "jahnavithota2011"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "/"
    assignees:
      - "jahnavithota2011"
    reviewers:
      - "jahnavithota2011"

  - package-ecosystem: "pip"
    directory: "/scripts/local-requirements"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "/"
    assignees:
      - "jahnavithota2011"
    reviewers:
      - "jahnavithota2011"
