set(TARGET_DEFINITIONS
        STM32F446xx
        TARGET_CORTEX
        TARGET_CORTEX_M
        TARGET_FAMILY_STM32
        TARGET_LIKE_CORTEX_M4
        TARGET_LIKE_MBED
        TARGET_M4
        TARGET_NAME=NUCLEO_F446RE
        TARGET_NUCLEO_F446RE
        TARGET_RELEASE
        TARGET_RTOS_M4_M7
        TARGET_STM
        TARGET_STM32F4
        TARGET_STM32F446RE
        TARGET_STM32F446xE
        TOOLCHAIN_GCC
        TOOLCHAIN_GCC_ARM
        )

add_library(mbed-os-target-interface INTERFACE)
target_include_directories(mbed-os-target-interface INTERFACE
        mbed-os
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/Include
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Config
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include1
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source
        mbed-os/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include
        mbed-os/cmsis/device
        mbed-os/cmsis/device/RTE/include
        mbed-os/cmsis/device/rtos/include
        mbed-os/drivers/include
        mbed-os/drivers/include/drivers
        mbed-os/events/include
        mbed-os/hal/include
        mbed-os/hal/include/hal
        mbed-os/hal/usb/include/usb
        mbed-os/platform/include
        mbed-os/platform/include/platform
        mbed-os/platform/include/platform/internal
        mbed-os/platform/mbed-trace/include
        mbed-os/rtos/include
        mbed-os/rtos/include/rtos
        mbed-os/rtos/include/rtos/internal
        mbed-os/storage/blockdevice/include
        mbed-os/targets/TARGET_STM
        mbed-os/targets/TARGET_STM/TARGET_STM32F4
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/CMSIS
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/Legacy
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE
        )
target_compile_definitions(mbed-os-target-interface INTERFACE ${MEMORY_DEFINITIONS} ${TARGET_DEFINITIONS})

add_library(mbed-os STATIC)
target_sources(mbed-os PRIVATE
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Config/RTX_Config.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Library/cmsis_os1.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7/irq_cm4f.S
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_delay.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_evflags.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_evr.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_kernel.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_lib.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_memory.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_mempool.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_msgqueue.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_mutex.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_semaphore.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_system.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_thread.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_timer.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/Source/os_systick.c
        mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/Source/os_tick_ptim.c
        mbed-os/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Source/mbed_tz_context.c
        mbed-os/cmsis/device/rtos/source/mbed_boot.c
        mbed-os/cmsis/device/rtos/source/mbed_rtos_rtx.c
        mbed-os/cmsis/device/rtos/source/mbed_rtx_handlers.c
        mbed-os/cmsis/device/rtos/source/mbed_rtx_idle.cpp
        mbed-os/cmsis/device/rtos/TOOLCHAIN_GCC_ARM/mbed_boot_gcc_arm.c
        mbed-os/drivers/source/AnalogIn.cpp
        mbed-os/drivers/source/AnalogOut.cpp
        mbed-os/drivers/source/BufferedSerial.cpp
        mbed-os/drivers/source/BusIn.cpp
        mbed-os/drivers/source/BusInOut.cpp
        mbed-os/drivers/source/BusOut.cpp
        mbed-os/drivers/source/CAN.cpp
        mbed-os/drivers/source/DigitalIn.cpp
        mbed-os/drivers/source/DigitalInOut.cpp
        mbed-os/drivers/source/DigitalOut.cpp
        mbed-os/drivers/source/FlashIAP.cpp
        mbed-os/drivers/source/I2C.cpp
        mbed-os/drivers/source/I2CSlave.cpp
        mbed-os/drivers/source/InterruptIn.cpp
        mbed-os/drivers/source/PortIn.cpp
        mbed-os/drivers/source/PortInOut.cpp
        mbed-os/drivers/source/PortOut.cpp
        mbed-os/drivers/source/PwmOut.cpp
        mbed-os/drivers/source/QSPI.cpp
        mbed-os/drivers/source/ResetReason.cpp
        mbed-os/drivers/source/SerialBase.cpp
        mbed-os/drivers/source/SerialWireOutput.cpp
        mbed-os/drivers/source/SFDP.cpp
        mbed-os/drivers/source/SPI.cpp
        mbed-os/drivers/source/SPISlave.cpp
        mbed-os/drivers/source/Ticker.cpp
        mbed-os/drivers/source/Timeout.cpp
        mbed-os/drivers/source/Timer.cpp
        mbed-os/drivers/source/TimerEvent.cpp
        mbed-os/drivers/source/UnbufferedSerial.cpp
        mbed-os/drivers/source/Watchdog.cpp
        mbed-os/events/source/equeue.c
        mbed-os/events/source/equeue_mbed.cpp
        mbed-os/events/source/equeue_posix.c
        mbed-os/events/source/EventQueue.cpp
        mbed-os/events/source/mbed_shared_queues.cpp
        mbed-os/hal/source/LowPowerTickerWrapper.cpp
        mbed-os/hal/source/mbed_compat.c
        mbed-os/hal/source/mbed_critical_section_api.c
        mbed-os/hal/source/mbed_flash_api.c
        mbed-os/hal/source/mbed_gpio.c
        mbed-os/hal/source/mbed_gpio_irq.c
        mbed-os/hal/source/mbed_itm_api.c
        mbed-os/hal/source/mbed_lp_ticker_api.c
        mbed-os/hal/source/mbed_lp_ticker_wrapper.cpp
        mbed-os/hal/source/mbed_pinmap_common.c
        mbed-os/hal/source/mbed_pinmap_default.cpp
        mbed-os/hal/source/mbed_ticker_api.c
        mbed-os/hal/source/mbed_us_ticker_api.c
        mbed-os/hal/source/mpu/mbed_mpu_v7m.c
        mbed-os/hal/source/mpu/mbed_mpu_v8m.c
        mbed-os/hal/source/static_pinmap.cpp
        mbed-os/hal/usb/source/mbed_usb_phy.cpp
        mbed-os/platform/cxxsupport/mstd_mutex.cpp
        mbed-os/platform/source/ATCmdParser.cpp
        mbed-os/platform/source/CriticalSectionLock.cpp
        mbed-os/platform/source/CThunkBase.cpp
        mbed-os/platform/source/DeepSleepLock.cpp
        mbed-os/platform/source/FileBase.cpp
        mbed-os/platform/source/FileHandle.cpp
        mbed-os/platform/source/FilePath.cpp
        mbed-os/platform/source/FileSystemHandle.cpp
        mbed-os/platform/source/LocalFileSystem.cpp
        mbed-os/platform/source/mbed_alloc_wrappers.cpp
        mbed-os/platform/source/mbed_application.c
        mbed-os/platform/source/mbed_assert.c
        mbed-os/platform/source/mbed_atomic_impl.c
        mbed-os/platform/source/mbed_board.c
        mbed-os/platform/source/mbed_critical.c
        mbed-os/platform/source/mbed_error.c
        mbed-os/platform/source/mbed_error_hist.c
        mbed-os/platform/source/mbed_interface.c
        mbed-os/platform/source/mbed_mem_trace.cpp
        mbed-os/platform/source/mbed_mktime.c
        mbed-os/platform/source/mbed_mpu_mgmt.c
        mbed-os/platform/source/mbed_os_timer.cpp
        mbed-os/platform/source/mbed_poll.cpp
        mbed-os/platform/source/mbed_power_mgmt.c
        mbed-os/platform/source/mbed_retarget.cpp
        mbed-os/platform/source/mbed_rtc_time.cpp
        mbed-os/platform/source/mbed_sdk_boot.c
        mbed-os/platform/source/mbed_semihost_api.c
        mbed-os/platform/source/mbed_stats.c
        mbed-os/platform/source/mbed_thread.cpp
        mbed-os/platform/source/mbed_wait_api_no_rtos.c
        mbed-os/platform/source/minimal-printf/mbed_printf_armlink_overrides.c
        mbed-os/platform/source/minimal-printf/mbed_printf_implementation.c
        mbed-os/platform/source/minimal-printf/mbed_printf_wrapper.c
        mbed-os/platform/source/Stream.cpp
        mbed-os/platform/source/SysTimer.cpp
        mbed-os/platform/source/TARGET_CORTEX_M/mbed_fault_handler.c
        mbed-os/platform/source/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.S
        mbed-os/rtos/source/ConditionVariable.cpp
        mbed-os/rtos/source/EventFlags.cpp
        mbed-os/rtos/source/Kernel.cpp
        mbed-os/rtos/source/Mutex.cpp
        mbed-os/rtos/source/Semaphore.cpp
        mbed-os/rtos/source/ThisThread.cpp
        mbed-os/rtos/source/Thread.cpp
        mbed-os/targets/TARGET_STM/analogin_api.c
        mbed-os/targets/TARGET_STM/analogout_api.c
        mbed-os/targets/TARGET_STM/can_api.c
        mbed-os/targets/TARGET_STM/gpio_api.c
        mbed-os/targets/TARGET_STM/gpio_irq_api.c
        mbed-os/targets/TARGET_STM/hal_tick_overrides.c
        mbed-os/targets/TARGET_STM/i2c_api.c
        mbed-os/targets/TARGET_STM/lp_ticker.c
        mbed-os/targets/TARGET_STM/mbed_crc_api.c
        mbed-os/targets/TARGET_STM/mbed_overrides.c
        mbed-os/targets/TARGET_STM/pinmap.c
        mbed-os/targets/TARGET_STM/port_api.c
        mbed-os/targets/TARGET_STM/pwmout_api.c
        mbed-os/targets/TARGET_STM/qspi_api.c
        mbed-os/targets/TARGET_STM/reset_reason.c
        mbed-os/targets/TARGET_STM/rtc_api.c
        mbed-os/targets/TARGET_STM/serial_api.c
        mbed-os/targets/TARGET_STM/sleep.c
        mbed-os/targets/TARGET_STM/stm_spi_api.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogin_device.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogout_device.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/flash_api.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/gpio_irq_device.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/pwmout_device.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/serial_device.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/spi_api.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/Legacy/stm32f4xx_hal_can_legacy.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_can.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_cec.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_crc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_cryp.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_cryp_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dcmi.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dcmi_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dfsdm.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma2d.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dsi.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_eth.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_exti.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_fmpi2c.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_fmpi2c_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_fmpsmbus.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_hash.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_hash_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_hcd.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2s.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2s_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_irda.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_iwdg.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_lptim.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_mmc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_nand.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_nor.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pccard.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_qspi.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rng.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sdram.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_smartcard.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_smbus.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_spdifrx.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sram.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_usart.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_wwdg.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_adc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_crc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_dac.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_dma2d.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_dma.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_exti.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_fmc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_fsmc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_gpio.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_i2c.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_lptim.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_pwr.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_rcc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_rng.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_rtc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_spi.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_tim.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_usart.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_utils.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/system_stm32f4xx.c
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TOOLCHAIN_GCC_ARM/startup_stm32f446xx.S
        mbed-os/targets/TARGET_STM/us_ticker.c
        mbed-os/targets/TARGET_STM/USBPhy_STM32.cpp
        mbed-os/targets/TARGET_STM/watchdog_api.c
        )
target_include_directories(mbed-os PUBLIC
        mbed-os/cmsis
        mbed-os/cmsis/TARGET_CORTEX_M
        mbed-os/drivers
        mbed-os/drivers/internal
        mbed-os/events
        mbed-os/events/internal
        mbed-os/features
        mbed-os/features/frameworks/mbed-client-randlib/mbed-client-randlib
        mbed-os/hal
        mbed-os/hal/usb
        mbed-os/platform
        mbed-os/platform/cxxsupport
        mbed-os/platform/internal
        mbed-os/platform/source
        mbed-os/platform/source/minimal-printf
        mbed-os/platform/source/TARGET_CORTEX_M
        mbed-os/rtos
        mbed-os/rtos/source
        mbed-os/rtos/source/TARGET_CORTEX
        mbed-os/rtos/source/TARGET_CORTEX/rtx4
        mbed-os/rtos/source/TARGET_CORTEX/rtx5/Include
        mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Config
        mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Include
        mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source
        mbed-os/targets/TARGET_STM
        mbed-os/targets/TARGET_STM/TARGET_STM32F4
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/CMSIS
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/Legacy
        mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE
        )
target_compile_options(mbed-os PRIVATE -w) # Disable all warnings from mbed code
target_compile_options(mbed-os PRIVATE $<$<COMPILE_LANGUAGE:C,CXX>:-include${CMAKE_SOURCE_DIR}/config/mbed_config.h>)
target_link_libraries(mbed-os PUBLIC ${TARGET}-board)
target_precompile_headers(mbed-os
        PUBLIC
        $<$<COMPILE_LANGUAGE:CXX>:${CMAKE_SOURCE_DIR}/mbed-os/mbed.h>
        )






