#pragma once

typedef enum CANID {

    // ERROR CAN IDs

    SAFETY_ERROR                = 0x100,
    ARM_ERROR,
    SCIENCE_ERROR,
    GIMBTONOMY_ERROR,

    // ARM CAN IDs

    ARM_RESET                   = 0x720,
    SET_OVERRIDE_FLAGS,

    SET_TURNTABLE_CONTROL_MODE  = 0x740,
    SET_SHOULDER_CONTROL_MODE,
    SET_ELBOW_CONTROL_MODE,
    SET_WRIST_CONTROL_MODE,
    SET_CLAW_CONTROL_MODE,

    SET_TURNTABLE_MOTIONDATA    = 0x745,
    SET_SHOULDER_MOTIONDATA,
    SET_ELBOW_MOTIONDATA,
    SET_WRIST_PITCH_MOTIONDATA,
    SET_WRIST_ROLL_MOTIONDATA,
    SET_CLAW_MOTIONDATA,
    SET_TOOL_TIP_DEPLOYMENT,

    RUN_WRIST_CALIBRATION       = 0x74C,
    RUN_CLAW_CALIBRATION,

    SET_PID_TUNING_MODE         = 0x750,
    SET_PID_DEADZONE,
    SET_JOINT_PID_P,
    SET_JOINT_PID_I,
    SET_JOINT_PID_D,
    SET_JOINT_PID_BIAS,

    REPORT_TURNTABLE_MOTION     = 0x758,
    REPORT_SHOULDER_MOTION,
    REPORT_ELBOW_MOTION,
    REPORT_WRIST_PITCH_MOTION,
    REPORT_WRIST_ROLL_MOTION,
    REPORT_CLAW_MOTION,
    FORCE_SENSOR_VALUE,

    // GIMBTONOMY CAN IDS
    SET_NEOPIXEL                = 0X784,
    NEOPIXEL_ACK,

    // SAFETY CAN IDS
    SET_ELBOW_ALERT_LIMIT       = 0x790,
    SET_CLAW_ALERT_LIMIT,
    SET_BICEP_ALERT_LIMIT,
    SET_WRIST_ALERT_LIMIT,
    SET_ALLEN_KEY_ALERT_LIMIT,
    SET_TURNTABLE_ALERT_LIMIT,

    SET_ELBOW_CONFIGURATION     =0x796,
    SET_CLAW_CONFIGURATION,
    SET_BICEP_CONFIGURATION,
    SET_WRIST_CONFIGURATION,
    SET_ALLEN_KEY_CONFIGURATION,
    SET_TURNTABLE_CONFIGURATION,   

    REPORT_ELBOW_SAFETY_DATA      =0x79C, 
    REPORT_CLAW_SAFETY_DATA,
    REPORT_BICEP_SAFETY_DATA,
    REPORT_WRIST_SAFETY_DATA,
    REPORT_ALLEN_KEY_SAFETY_DATA,
    REPORT_TURNTABLE_SAFETY_DATA,
    REPORT_TEMP_DATA

} CANID;
