#pragma once

typedef enum {

    // ERROR CAN IDs

    SAFETY_ERROR                = 0x100,
    ARM_ERROR,
    SCIENCE_ERROR,
    GIMBTONOMY_ERROR,

    // ARM CAN IDs

    SET_TURNTABLE_CONTROL_MODE  = 0x740,
    SET_SHOULDER_CONTROL_MODE,
    SET_ELBOW_CONTROL_MODE,
    SET_WRIST_CONTROL_MODE,
    SET_CLAW_CONTROL_MODE,

    SET_TURNTABLE_MOTION_VAL    = 0x745,
    SET_SHOULDER_MOTION_VAL,
    SET_ELBOW_MOTION_VAL,
    SET_WRIST_PITCH_MOTION_VAL,
    SET_WRIST_ROLL_MOTION_VAL,
    SET_CLAW_MOTION_VAL,
    SET_TOOL_TIP_DEPLOYMENT,

    RUN_WRIST_CALIBRATION       = 0x74C,
    RUN_CLAW_CALIBRATION,

    SET_PID_TUNING_MODE         = 0x750,
    SET_PID_DEADZONE,
    SET_JOINT_PID_P,
    SET_JOINT_PID_I,
    SET_JOINT_PID_D,
    SET_JOINT_PID_BIAS,

    TURNTABLE_POSITION          = 0x758,
    SHOULDER_POSITION,
    ELBOW_POSITION,
    WRIST_PITCH_POSITION,
    WRIST_ROLL_POSITION,
    CLAW_POSITION,
    FORCE_SENSOR_VALUE

} CANCommandIDs;