#pragma once

typedef enum ROSID {
    // ACTUATOR IDS
    TURNTABLEACTUATORID,
    SHOULDERACTUATORID,
    ELBOWACTUATORID,
    WRISTLEFTACTUATORID,
    WRISTRIGHTACTUATORID,
    CLAWACTUATORID,
    // PID PARAMETER IDS
    P = 0,
    I,
    D,
} ROSID;