#pragma once

// TODO: these defines should go in hw bridge

#define PDB_VBAT_RAIL_NOMINAL_VOLTAGE 24.0
#define PDB_VBAT_RAIL_MIN_THRESHOLD   18.0
#define PDB_VBAT_RAIL_MAX_THRESHOLD   25.2

#define PDB_24V_RAIL_NOMINAL_VOLTAGE 24.0
#define PDB_24V_RAIL_MIN_THRESHOLD   23.0
#define PDB_24V_RAIL_MAX_THRESHOLD   25.0

#define PDB_17V_RAIL_NOMINAL_VOLTAGE 17.0
#define PDB_17V_RAIL_MIN_THRESHOLD   16.5
#define PDB_17V_RAIL_MAX_THRESHOLD   17.5

#define PDB_5V_RAIL_NOMINAL_VOLTAGE 5.0
#define PDB_5V_RAIL_MIN_THRESHOLD   4.5
#define PDB_5V_RAIL_MAX_THRESHOLD   5.5

#define PDB_TEMPERATURE_MIN_THRESHOLD 10.0
#define PDB_TEMPERATURE_MAX_THRESHOLD 50.0

#define PDB_5V_LOAD1_DIAG_EN 1
#define PDB_5V_LOAD2_DIAG_EN 0
#define PDB_5V_LOAD3_DIAG_EN 0
#define PDB_5V_LOAD4_DIAG_EN 0
#define PDB_5V_LOAD5_DIAG_EN 0
#define PDB_17V_LOAD_DIAG_EN 1

#define PDB_RX_CAN_PROCESSING_PERIOD      2ms
#define PDB_TX_CAN_PROCESSING_PERIOD      2ms
#define PDB_LOAD_MONITORING_PERIOD        1000ms
#define PDB_RAIL_MONITORING_PERIOD        500ms
#define PDB_TEMPERATURE_MONITORING_PERIOD 1000ms
